version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    assignees:
      - "olvlvl"
    commit-message:
      prefix: "build(deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
    assignees:
      - "olvlvl"
    commit-message:
      prefix: "ci"
