<?php

/*
 * (c) Olivier Laviale <olivier.laviale@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace olvlvl\ComposerAttributeCollector;

use Attribute;
use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\Script\Event;
use ReflectionAttribute;
use ReflectionClass;
use ReflectionException;
use ReflectionMethod;

use function array_map;
use function file_get_contents;
use function file_put_contents;
use function implode;
use function interface_exists;
use function is_string;
use function spl_autoload_register;
use function str_contains;
use function var_export;

/**
 * @internal
 */
final class Plugin implements PluginInterface, EventSubscriberInterface
{
    /**
     * @uses onPostAutoloadDump
     */
    public static function getSubscribedEvents(): array
    {
        return [
            'post-autoload-dump' => 'onPostAutoloadDump',
        ];
    }

    public function activate(Composer $composer, IOInterface $io): void
    {
    }

    public function deactivate(Composer $composer, IOInterface $io): void
    {
    }

    public function uninstall(Composer $composer, IOInterface $io): void
    {
    }

    public static function onPostAutoloadDump(Event $event): void
    {
        $composer = $event->getComposer();
        $io = $event->getIO();
        $vendorDir = $composer->getConfig()->get('vendor-dir');
        assert(is_string($vendorDir));
        $filepath = "$vendorDir/attributes.php";

        $io->write('<info>Generating attributes file</info>');
        self::dump($event->getComposer(), $io, $filepath);
        $io->write('<info>Generated attributes file</info>');
    }

    public static function dump(
        Composer $composer,
        IOInterface $io,
        string $filepath,
        AutoloadsBuilder $autoloadsBuilder = null,
        ClassMapBuilder $classMapBuilder = null
    ): void {
        $autoloadsBuilder ??= new AutoloadsBuilder();
        $classMapBuilder ??= new ClassMapBuilder();

        $autoloads = $autoloadsBuilder->buildAutoloads($composer);
        $classMap = $classMapBuilder->buildClassMap($autoloads);

        self::setupAutoload($classMap);

        $collection = self::collectAttributes($classMap, $io);
        $code = self::render($collection);

        file_put_contents($filepath, $code);
    }

    /**
     * @param array<class-string, non-empty-string> $classMap
     */
    private static function setupAutoload(array $classMap): void
    {
        spl_autoload_register(function (string $class) use ($classMap) {
            $file = $classMap[$class] ?? null;
            if ($file) {
                require_once $file;
            }
        });
    }

    /**
     * @param array<class-string, non-empty-string> $classMap
     *
     * @throws ReflectionException
     */
    private static function collectAttributes(array $classMap, IOInterface $io): Collector
    {
        $collector = new Collector();

        foreach ($classMap as $class => $filepath) {
            $content = file_get_contents($filepath);

            assert(is_string($content));

            if (!str_contains($content, '#[')) {
                continue;
            }

            if (interface_exists($class)) {
                continue;
            }

            $classReflection = new ReflectionClass($class);

            if (self::isAttribute($classReflection)) {
                continue;
            }

            $attributes = $classReflection->getAttributes();

            foreach ($attributes as $attribute) {
                if (self::isAttributeIgnored($attribute)) {
                    continue;
                }

                $io->debug("Found attribute {$attribute->getName()} on $class");

                $collector->addTargetClass($attribute, $classReflection);
            }

            foreach ($classReflection->getMethods(ReflectionMethod::IS_PUBLIC) as $methodReflection) {
                foreach ($methodReflection->getAttributes() as $attribute) {
                    if (self::isAttributeIgnored($attribute)) {
                        continue;
                    }

                    $io->debug("Found attribute {$attribute->getName()} on $class::{$methodReflection->name}");

                    $collector->addTargetMethod($attribute, $methodReflection);
                }
            }
        }

        return $collector;
    }

    public static function render(Collector $collector): string
    {
        $targetClassesCode = self::renderTargetClasses($collector->classes);
        $targetMethodsCode = self::renderTargetMethods($collector->methods);

        return <<<PHP
        <?php

        // attributes.php @generated by https://github.com/olvlvl/composer-attribute-collector

        namespace olvlvl\ComposerAttributeCollector;

        Attributes::with(fn () => new Collection(
            targetClasses: [
        $targetClassesCode
            ],
            targetMethods: [
        $targetMethodsCode
            ],
        ));
        PHP;
    }

    /**
     * @param array<class-string, TargetClassRaw[]> $classes
     */
    private static function renderTargetClasses(array $classes): string
    {
        $code = '';

        foreach ($classes as $attribute => $targets) {
            $code .= "        \\$attribute::class => [\n";
            foreach ($targets as $target) {
                $argumentsCode = self::renderArguments($target->arguments);
                $code .= <<<PHP
                            [ $argumentsCode, \\$target->name::class ],

                PHP;
            }
            $code .= "        ],\n";
        }

        return $code;
    }

    /**
     * @param array<class-string, TargetMethodRaw[]> $methods
     */
    private static function renderTargetMethods(array $methods): string
    {
        $code = '';

        foreach ($methods as $attribute => $targets) {
            $code .= "        \\$attribute::class => [\n";
            foreach ($targets as $target) {
                $argumentsCode = self::renderArguments($target->arguments);
                $code .= <<<PHP
                            [ $argumentsCode, \\$target->class::class, '$target->name' ],

                PHP;
            }
            $code .= "        ],\n";
        }

        return $code;
    }

    /**
     * @param mixed[] $array
     */
    private static function renderArguments(array $array): string
    {
        return '[' . implode(', ', array_map(fn($v) => var_export($v, true), $array)) . ']';
    }

    /**
     * Determines if a class is an attribute.
     *
     * @param ReflectionClass<object> $classReflection
     */
    private static function isAttribute(ReflectionClass $classReflection): bool
    {
        foreach ($classReflection->getAttributes() as $attribute) {
            if ($attribute->getName() === Attribute::class) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param ReflectionAttribute<object> $attribute
     */
    private static function isAttributeIgnored(ReflectionAttribute $attribute): bool
    {
        static $ignored = [
            \ReturnTypeWillChange::class => true,
        ];

        return isset($ignored[$attribute->getName()]);
    }
}
