name: cases
on:
  push:
    branches:
    - main
    - "2.**"
    - "case-**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  case-incompatible-signature:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        includes:
          - php-version: "8.0"
            composer-version: "v2.3.0"
            composer-tweak: "--prefer-lowest"
          - php-version: "8.5"
            composer-version: "v2"
            composer-tweak: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:${{ matrix.composer-version }}
      - name: Run case
        run: |
          cd cases/incompatible-signature
          composer update --no-interaction --no-progress ${{ matrix.composer-tweak }}

  case-symfony:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        includes:
          - php-version: "8.2"
            composer-version: "v2.3.0"
          - php-version: "8.5"
            composer-version: "latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:${{ matrix.composer-version }}
      - name: Run case
        run: |
          cd cases/symfony
          composer install --no-interaction --no-progress
          php test.php

  case-laravel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        includes:
          - php-version: "8.2"
            composer-version: "v2.3.0"
          - php-version: "8.5"
            composer-version: "latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1
          tools: composer:${{ matrix.composer-version }}
      - name: Run case
        run: |
          cd cases/laravel
          composer install --no-interaction --no-progress
          php test.php
