name: code-style

on:
  push:
    branches:
      - '!case-**'
  pull_request:
    branches:
      - '!case-**'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: "8.0"
        ini-values: memory_limit=-1
        tools: phpcs, cs2pr
    - name: Run PHP Code Sniffer
      run: phpcs -q --report=checkstyle | cs2pr
