name: quality

on:
  push:
    branches-ignore:
    - 'case-**'
  pull_request:
    branches-ignore:
    - 'case-**'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: "8.5"
        ini-values: memory_limit=-1
        tools: phpcs, cs2pr
    - name: Run PHP Code Sniffer
      run: phpcs -q --report=checkstyle | cs2pr

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.5"
        ini-values: memory_limit=-1
        tools: composer:v2
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.composer/cache
          vendor
        key: phpstan-deps

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Analyze
      run: vendor/bin/phpstan
